Repository PTCMR/PTCMR_BACK, pull requests merged in 2024-08, with the labels that each got.

#8 [#5] Feat product soft delete
  .idea/compiler.xml
  .idea/dataSources.xml
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/soon/PTCMR_Back/domain/product/controller/ProductController.java
  src/main/java/soon/PTCMR_Back/domain/product/entity/Product.java
  src/main/java/soon/PTCMR_Back/domain/product/repository/ProductRepository.java
  src/main/java/soon/PTCMR_Back/domain/product/service/ProductService.java
  src/main/java/soon/PTCMR_Back/global/entity/ErrorCode.java
  src/main/java/soon/PTCMR_Back/global/exception/PTCMRException.java
  src/main/java/soon/PTCMR_Back/global/exception/ProductNotFoundException.java
  src/main/resources/static/docs/index.html
  src/test/java/soon/PTCMR_Back/PTCMRBackApplicationTests.java
  src/test/java/soon/PTCMR_Back/domain/product/controller/ProductControllerDocsTest.java
  src/test/java/soon/PTCMR_Back/domain/product/controller/ProductControllerTest.java
  src/test/java/soon/PTCMR_Back/domain/product/service/ProductServiceTest.java
Labels: feat

#15 [#10] Feat 팀 생성
  src/docs/asciidoc/index.adoc
  src/main/java/soon/PTCMR_Back/domain/product/service/ProductService.java
  src/main/java/soon/PTCMR_Back/domain/team/controller/TeamController.java
  src/main/java/soon/PTCMR_Back/domain/team/dto/reqeust/TeamCreateRequest.java
  src/main/java/soon/PTCMR_Back/domain/team/entity/NotificationSchedule.java
  src/main/java/soon/PTCMR_Back/domain/team/entity/Team.java
  src/main/java/soon/PTCMR_Back/domain/team/repository/TeamMemberJpaRepository.java
  src/main/java/soon/PTCMR_Back/domain/team/repository/TeamMemberRepository.java
  src/main/java/soon/PTCMR_Back/domain/team/repository/TeamRepository.java
  src/main/java/soon/PTCMR_Back/domain/team/service/TeamManager.java
  src/main/java/soon/PTCMR_Back/domain/team/service/TeamService.java
  src/test/java/soon/PTCMR_Back/domain/member/MockUser.java
  src/test/java/soon/PTCMR_Back/domain/team/controller/TeamControllerDocsTest.java
  src/test/java/soon/PTCMR_Back/domain/team/controller/TeamControllerTest.java
  src/test/java/soon/PTCMR_Back/domain/team/service/TeamServiceTest.java
Labels: Feat

#19 [#17] Team Update 구현
  src/docs/asciidoc/index.adoc
  src/main/java/soon/PTCMR_Back/domain/member/repository/MemberRepository.java
  src/main/java/soon/PTCMR_Back/domain/team/controller/TeamController.java
  src/main/java/soon/PTCMR_Back/domain/team/dto/reqeust/TeamUpdateRequest.java
  src/main/java/soon/PTCMR_Back/domain/team/dto/response/TeamDetails.java
  src/main/java/soon/PTCMR_Back/domain/team/entity/Team.java
  src/main/java/soon/PTCMR_Back/domain/team/repository/TeamMemberJpaRepository.java
  src/main/java/soon/PTCMR_Back/domain/team/repository/TeamMemberRepository.java
  src/main/java/soon/PTCMR_Back/domain/team/repository/TeamRepository.java
  src/main/java/soon/PTCMR_Back/domain/team/service/TeamManager.java
  src/main/java/soon/PTCMR_Back/domain/team/service/TeamService.java
  src/main/java/soon/PTCMR_Back/global/entity/ErrorCode.java
  src/main/java/soon/PTCMR_Back/global/exception/InvalidMemberException.java
  src/test/java/soon/PTCMR_Back/domain/member/MockUser.java
  src/test/java/soon/PTCMR_Back/domain/team/controller/TeamControllerDocsTest.java
  src/test/java/soon/PTCMR_Back/domain/team/controller/TeamControllerTest.java
  src/test/java/soon/PTCMR_Back/domain/team/service/TeamServiceTest.java
Labels: Test, Feat

#23 [#22] Product 리팩토링
  .gitmodules
  .idea/.gitignore
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/misc.xml
  .idea/vcs.xml
  src/docs/asciidoc/index.adoc
  src/main/java/soon/PTCMR_Back/domain/product/controller/ProductController.java
  src/main/java/soon/PTCMR_Back/domain/product/dto/request/ProductCreateRequest.java
  src/main/java/soon/PTCMR_Back/domain/product/dto/request/ProductUpdateRequest.java
  src/main/java/soon/PTCMR_Back/domain/product/dto/response/ProductDetailResponse.java
  src/main/java/soon/PTCMR_Back/domain/product/entity/Product.java
  src/main/java/soon/PTCMR_Back/domain/product/service/ProductService.java
  src/test/java/soon/PTCMR_Back/domain/product/controller/ProductControllerDocsTest.java
  src/test/java/soon/PTCMR_Back/domain/product/controller/ProductControllerTest.java
  src/test/java/soon/PTCMR_Back/domain/product/entity/ProductTest.java
  src/test/java/soon/PTCMR_Back/domain/product/service/ProductServiceTest.java
Labels: Refactor

#27 [#24] Product 조회 기능 구현
  .idea/compiler.xml
  .idea/misc.xml
  src/docs/asciidoc/index.adoc
  src/main/java/soon/PTCMR_Back/domain/product/controller/ProductController.java
  src/main/java/soon/PTCMR_Back/domain/product/dto/ProductPaginationDto.java
  src/main/java/soon/PTCMR_Back/domain/product/dto/request/ProductPaginationRequest.java
  src/main/java/soon/PTCMR_Back/domain/product/dto/response/ProductPaginationResponseWrapper.java
  src/main/java/soon/PTCMR_Back/domain/product/entity/ProductSortOption.java
  src/main/java/soon/PTCMR_Back/domain/product/repository/ProductPaginationRepository.java
  src/main/java/soon/PTCMR_Back/domain/product/service/ProductService.java
  src/main/java/soon/PTCMR_Back/global/config/QueryDslConfiguration.java
  src/test/java/soon/PTCMR_Back/domain/product/controller/ProductControllerTest.java
  src/test/java/soon/PTCMR_Back/domain/product/entity/ProductTest.java
  src/test/java/soon/PTCMR_Back/domain/product/service/ProductServiceTest.java
Labels: Feat

#30 [#29] Setting test용 db 추가
  .idea/modules.xml
  .idea/modules/PTCMR_back.test.iml
  build.gradle
Labels: Test
